### ISSUE TITLE
Failed to unRoot

### ISSUE THREAD

**Issue by illnino** [jakev/unrootbeer#1]
The app still could detect the device has been Rooted. May I know how could I check why it is not working?

### Galaxy S4

Rom: Android 5.0.2 CyanogenMod (12-20150731-UNOFFICIAL-i9500)
Xposed: 3.0 alpha4

### Galaxy S6

ROM: Android 6.0.1
Xposed: 3.0 alpha4

**Comment by jakev** [comment]
Which app are you having issues with? Can you provide the APK? Also, have you confirmed the app is using RootBeer?

**Comment by illnino** [comment]
I am afraid I cant provide it due to contract agreement. But by de-compling the apk, I could see RootBeer library is used.

Is there a way for me to figure out why it did not work properly?

**Comment by jakev** [comment]
Understood. Can you confirm that RootBeer is the only library performing the root checking? I've often seen multiple methods used in combination.

If you're confident it's only RootBeer, can you try to find a version? Also, can you check if there are any errors in a logcat?

**Comment by illnino** [comment]
It looks like they have implemented other root checking techniques. 

Btw, UnRootBeer could successfully bypass RootBeer Sample App.
